export const STRING = {
  apiError: 'Không kết nối được với máy chủ',
  login: {
    login: 'Đăng nhập',
    register: 'Đăng ký',
    unHaveAcc: 'Chưa có tài khoản ',
    username: 'Tên đăng nhập',
    email: 'Email',
    password: 'Mật khẩu',
    cfPassword: 'Nhập lại Mật khẩu',
    rememberPwd: 'Ghi nhớ đăng nhập',
    auth: 'Xác thực'
  },

  picture: 'Hình ảnh',
  btn: {
    save: 'Lưu',
    confirm: 'Xác nhận',
    checkNow: 'Xem ngay',
    buyNow: 'Mua ngay',
    addToCart: 'Thêm vào giỏ hàng',
    checkout: 'Thanh toán',
  },
  valid: {
    notBeBlank: ' không được bỏ trống',
    inValid: ' không hợp lệ',
    pwd: 'Password must be more than 8 characters.'
  },
  changePwd: {
    newPwd: 'Mật khẩu mới',
    inputNewPwd: 'Nhập vào mật khẩu mới',
    currentPwd: 'Mật khẩu cũ',
    inputCurrentPwd: 'Nhập vào mật khẩu cũ',
    confirmPwd: 'Xác nhận mật khẩu mới',
    changePwdFistTime: 'Đổi mật khẩu lần đầu',
    changePwd: 'Đổi mật khẩu',
    changePwdSucces:
      'Đổi mật khẩu thành công, bạn có muốn lưu lại mật khẩu mới?',
  },
  route: {
    delivery: 'Giao hàng',
    history: 'Lịch sử',
    dashboard: 'Thống kê',
    profile: 'Thông tin cá nhân',
    home: 'Trang chủ',
    combo: 'Combo'
  },
  popup: {
    loginErr: 'Đăng nhập thất bại',
    success: 'Thành công',
    loginToContinue: 'Đăng nhập để tiếp tục',
  },
  product: {
    product: 'Sản phẩm',
    costume: 'Trang phục',
    accessory: 'Phụ kiện',
    relaProduct: 'Sản phẩm liên quan',
    ID: 'Mã sp',
    Image: 'Hình ảnh',
    Name: 'Tên sản phẩm',
    Price: 'Giá',
    Quantity: 'Số lượng',
    Total: 'Tổng',
    Actions: 'Hành động',
    Checkout: 'Thanh toán',
  },
  support: 'Hỗ trợ',
  about: 'Về chúng tôi',
  contact: 'Liên hệ',
  terms: 'Điều khoản sử dụng',
  rental: 'Chính sách và thủ tục cho thuê',
  size: 'Kích cỡ',
  phone: 'Số điện thoại',
  sex: 'Giới tính',
  male: 'Nam',
  female: 'Nữ',
  name: 'Họ và tên',
  empty: 'Không có sản phẩm nào',
  cart: 'Giỏ hàng',
  odDetail:'Chi tiết đơn hàng',
  deliOption:'Phương thức nhận hàng',
  ship:'Giao hàng',
  takeAway:'Lấy tại cửa hàng',
  address:'Địa chỉ',
  addressNote:'Ghi chú',
  ward:'Phường',
  district:'Quận',
  city:'Tỉnh/ Thành phố',
  labelAs:'Điểm nhận hàng',
  company:'Văn phòng',
  home:'Nhà riêng',
  paymentMth:'Phương thức thanh toán',
  bank:'Chuyển khoản',
  Cash:'Tiền mặt',
  myOd:'Đơn hàng của tôi',
};
